#!/bin/sh
clear
xdotool keydown Alt_L key +k keyup Alt_L 
sleep 2
xdotool key Return && xdotool type " wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
xdotool key Return
sleep 3
xdotool type "clear" && xdotool key Return
sleep 2
xdotool type "sudo apt-get install ./google-chrome-stable_current_amd64.deb" 
sleep 2
xdotool key Return
Source $HOME/zsh/ghubb
